### POST Endpoint for creating new employee
POST http://127.0.0.1:8000/api/v1/employees
Content-Type: application/json
Accept: application/json

{"firstNameAndLastName": "Q0IUnw0V7AH1iAcDItUtXvvfhyzsZna8aeB3PAJeEAAXBUmGVVQSFmXg8RA0b24TB37Etf70cQfJwSuwjCRecNW8s5tbllYWRsqBSGfFiuIrHduyHuAkXI6JFUf9IT2dvO2sz58Ylcy9p89voWiCOD9ctsfoPVGYlajHIxLLhWesf1aP1Q6cj5yxjqyxZNAq5YmojT5ihCjj8pOgARuFRJiAPzPmyDykSrywQqIatWU1jhF8TWuPtZRbVR2ZNqWxU2K1OUQb6XcN4mgF8BDKEctLyURpVBFGH79z5vgtVFKGzwcv8hCALHthapWKe7sl3lh9dyHRPXJ8TQNJpwAr7DilZIQXK3ovUUIwShUG2ViMTgcGOYDQLDiRDhh2LuVXmnZyCwjsQvN5MZLkkD1SHvnaxr2773PWF3ejMrxpvqgYxS83dWaeUNZWVgGTvIlhXwXxJ9oYewUYx0BW3Xvd3ZtCRl2AlJ6YHYXPoz6sbHTJ6Z1M5NUVE3k72VK1OM1mx6k"}
###