controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_v1:
    resource:
        path: ../src/Controller/Api/V1
        namespace: App\Controller\Api\V1
    prefix: '/api/v1/'
    type: attribute
